// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY3uqKa7UoB7F28bU1YPbRP3Ze3qLVGrw',
    appId: '1:111585473135:web:c8a74315b04a1a34c4139a',
    messagingSenderId: '111585473135',
    projectId: 'eco-zone-c4a29',
    authDomain: 'eco-zone-c4a29.firebaseapp.com',
    storageBucket: 'eco-zone-c4a29.firebasestorage.app',
    measurementId: 'G-9E2L8YSBJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_qaBvS1vS8gM2qZajlYkbfbQZknDgBY',
    appId: '1:111585473135:android:7feea01ec91c8209c4139a',
    messagingSenderId: '111585473135',
    projectId: 'eco-zone-c4a29',
    storageBucket: 'eco-zone-c4a29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiUWS9sNLjKJwOlTXOQPEJEnc3mAw2Dm8',
    appId: '1:111585473135:ios:e0d8dec110e53c1fc4139a',
    messagingSenderId: '111585473135',
    projectId: 'eco-zone-c4a29',
    storageBucket: 'eco-zone-c4a29.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiUWS9sNLjKJwOlTXOQPEJEnc3mAw2Dm8',
    appId: '1:111585473135:ios:e0d8dec110e53c1fc4139a',
    messagingSenderId: '111585473135',
    projectId: 'eco-zone-c4a29',
    storageBucket: 'eco-zone-c4a29.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY3uqKa7UoB7F28bU1YPbRP3Ze3qLVGrw',
    appId: '1:111585473135:web:f314131e971d9178c4139a',
    messagingSenderId: '111585473135',
    projectId: 'eco-zone-c4a29',
    authDomain: 'eco-zone-c4a29.firebaseapp.com',
    storageBucket: 'eco-zone-c4a29.firebasestorage.app',
    measurementId: 'G-02DWYZHNTT',
  );
}
